
import { Product, User } from "./types";

// Sample users data
export const users: User[] = [
  {
    id: "admin-1",
    name: "Admin User",
    email: "admin@example.com",
    role: "admin",
  },
  {
    id: "customer-1",
    name: "John Customer",
    email: "customer@example.com",
    role: "customer",
  },
];

// Sample products data
export const products: Product[] = [
  {
    id: "prod-1",
    name: "Premium Wireless Headphones",
    description: "High-quality wireless headphones with noise cancellation technology. Features Bluetooth 5.0, 40 hours battery life, comfortable over-ear design, and crystal-clear sound quality. Perfect for travel, work, or everyday use.",
    price: 199.99,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cHJvZHVjdHxlbnwwfHwwfHx8MA%3D%3D",
    category: "Electronics",
    stock: 45,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-2",
    name: "Smart Fitness Tracker",
    description: "Track your fitness goals with heart rate monitoring and GPS. This advanced tracker includes sleep monitoring, workout detection, and water resistance up to 50m. Syncs wirelessly with your smartphone for real-time stats.",
    price: 129.99,
    originalPrice: 149.99,
    image: "https://images.unsplash.com/photo-1576243345690-4e4b79b63288?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGZpdG5lc3MlMjB3YXRjaHxlbnwwfHwwfHx8MA%3D%3D",
    category: "Fitness",
    stock: 78,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-3",
    name: "Designer Sunglasses",
    description: "Fashionable sunglasses with UV protection. Italian design with polarized lenses, lightweight frame, and premium carrying case. Available in multiple colors, these sunglasses combine style and protection.",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8cHJvZHVjdHxlbnwwfHwwfHx8MA%3D%3D",
    category: "Fashion",
    stock: 120,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-4",
    name: "Coffee Maker",
    description: "Programmable coffee maker with built-in grinder. Features 10-cup capacity, programmable timer, multiple brew strengths, and auto shut-off. Stainless steel construction with an elegant design that complements any kitchen.",
    price: 149.99,
    originalPrice: 179.99,
    image: "https://images.unsplash.com/photo-1520608760-eff2c38b0515?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y29mZmVlJTIwbWFrZXJ8ZW58MHx8MHx8fDA%3D",
    category: "Home",
    stock: 32,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-5",
    name: "Smartphone Stand",
    description: "Adjustable stand for smartphones and tablets. Made from premium aluminum with non-slip base and cable management. Supports devices up to 12 inches and adjusts to multiple viewing angles for optimal comfort.",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHBob25lJTIwc3RhbmR8ZW58MHx8MHx8fDA%3D",
    category: "Accessories",
    stock: 200,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-6",
    name: "Wireless Gaming Mouse",
    description: "Precision wireless mouse for gaming enthusiasts. Features 16000 DPI optical sensor, 7 programmable buttons, customizable RGB lighting, and up to 60 hours battery life. Ultra-responsive with 1ms polling rate.",
    price: 79.99,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8Z2FtaW5nJTIwbW91c2V8ZW58MHx8MHx8fDA%3D",
    category: "Gaming",
    stock: 65,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-7",
    name: "Leather Wallet",
    description: "Genuine leather wallet with RFID protection. Handcrafted from top-grain leather with 8 card slots, 2 bill compartments, and a coin pocket. The RFID blocking technology protects your personal information from theft.",
    price: 49.99,
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bGVhdGhlciUyMHdhbGxldHxlbnwwfHwwfHx8MA%3D%3D",
    category: "Fashion",
    stock: 110,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-8",
    name: "Smart Indoor Plant Pot",
    description: "Self-watering pot with soil moisture monitoring. This innovative pot monitors moisture, light, and temperature to keep your plants healthy. The companion app alerts you when your plant needs attention.",
    price: 39.99,
    image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHNtYXJ0JTIwcGxhbnQlMjBwb3R8ZW58MHx8MHx8fDA%3D",
    category: "Home",
    stock: 48,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-9",
    name: "Mechanical Keyboard",
    description: "Premium mechanical keyboard with RGB backlighting. Features hot-swappable switches, N-key rollover, customizable lighting effects, and durable PBT keycaps. Connect via USB-C or Bluetooth to up to 3 devices.",
    price: 129.99,
    originalPrice: 159.99,
    image: "https://images.unsplash.com/photo-1563191911-e65f8a94594a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fG1lY2hhbmljYWwlMjBrZXlib2FyZHxlbnwwfHwwfHx8MA%3D%3D",
    category: "Electronics",
    stock: 35,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-10",
    name: "Smart Doorbell Camera",
    description: "HD video doorbell with motion detection and two-way audio. Get instant alerts when someone approaches your door, speak with visitors remotely, and view recorded footage. Works with Alexa and Google Home.",
    price: 179.99,
    image: "https://images.unsplash.com/photo-1588968842349-501c6014e431?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fGRvb3JiZWxsJTIwY2FtZXJhfGVufDB8fDB8fHww",
    category: "Smart Home",
    stock: 25,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-11",
    name: "Portable Blender",
    description: "Rechargeable portable blender for smoothies and shakes on the go. This USB-rechargeable blender makes 10-12 beverages on a single charge. Compact design with 350ml capacity is perfect for travel, gym, or office.",
    price: 34.99,
    originalPrice: 44.99,
    image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8cG9ydGFibGUlMjBibGVuZGVyfGVufDB8fDB8fHww",
    category: "Kitchen",
    stock: 85,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-12",
    name: "Electric Skateboard",
    description: "Powerful electric skateboard with 22mph top speed and 12-mile range. Features dual 350W motors, regenerative braking, and three riding modes. The remote control offers precise speed and braking adjustment.",
    price: 399.99,
    image: "https://images.unsplash.com/photo-1519861531473-9200262188bf?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZWxlY3RyaWMlMjBza2F0ZWJvYXJkfGVufDB8fDB8fHww",
    category: "Sports",
    stock: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-13",
    name: "Air Purifier",
    description: "HEPA air purifier for rooms up to 500 sq ft. Features a 3-stage filtration system that removes 99.97% of airborne particles, including allergens, dust, and odors. Quiet operation with sleep mode and filter replacement indicator.",
    price: 149.99,
    originalPrice: 179.99,
    image: "https://images.unsplash.com/photo-1626489013583-9151173b71fa?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8YWlyJTIwcHVyaWZpZXJ8ZW58MHx8MHx8fDA%3D",
    category: "Home",
    stock: 42,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-14",
    name: "Ergonomic Office Chair",
    description: "Adjustable office chair with lumbar support and breathable mesh. Features adjustable height, tilt, armrests, and headrest for personalized comfort. The breathable mesh back keeps you cool during long work sessions.",
    price: 249.99,
    image: "https://images.unsplash.com/photo-1579130781921-76e18d180258?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8b2ZmaWNlJTIwY2hhaXJ8ZW58MHx8MHx8fDA%3D",
    category: "Furniture",
    stock: 20,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-15",
    name: "Smart Water Bottle",
    description: "Water bottle with hydration tracking and temperature display. This 20oz bottle glows to remind you to drink water and syncs with your smartphone to track your hydration goals. Keeps drinks cold for 24 hours or hot for 12 hours.",
    price: 59.99,
    image: "https://images.unsplash.com/photo-1570087935627-98b7954fa4ee?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHdhdGVyJTIwYm90dGxlfGVufDB8fDB8fHww",
    category: "Fitness",
    stock: 55,
    featured: true,
    createdAt: new Date().toISOString(),
  }
];

export const categories = [...new Set(products.map(product => product.category))];
